apiVersion: skaffold/v4beta10
kind: Config
# requires:
# - configs: ["monitoring"]
#   path: ./stacks/monitoring/skaffold.yaml
# - configs: ["infra"]
#   path: ./stacks/cluster-infra/skaffold.yaml
# - configs: ['cluster-secrets']
#   path: ./secrets/skaffold.yaml

metadata:
  name: valhalla

manifests:
  rawYaml:
  - ./stacks/namespaces.yaml

deploy:
  helm:
    releases:
    # Hate having to do this but see the issue for the reasoning:
    # https://github.com/GoogleContainerTools/skaffold/issues/2741
    - name: headlamp
      repo: https://headlamp-k8s.github.io/headlamp/
      remoteChart: headlamp
    - name: gitea
      repo: https://dl.gitea.com/charts/
      remoteChart: gitea
    hooks:
      after:
      - host:
          command: ["sh", "-c", "echo '\n************** Creating headlamp token **************\n'"]
      - host:
          command: ["sh", "-c", "kubectl create token headlamp --namespace default"]
      - host:
          command: ["sh", "-c", "echo '\n*****************************************************\n'"]
# profiles:
# - name: tools
#   patches:
#   - op: add
#     path: /manifests/rawYaml/-
#     value: ./stacks/tools/**/*.yaml

portForward:
- resourceName: headlamp
  resourceType: service
  namespace: default
  port: 80
  localPort: 8082
