apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: drogon
manifests:
  rawYaml:
    - ./stacks/namespaces.yaml
    - ./stacks/cluster-infra/**/*.yaml
    # - ./stacks/media/**/*.yaml
    - ./stacks/tools/**/*.yaml

deploy:
  helm:
    releases:
    # HELM: Traefik Proxy
    - name: traefik
      repo: https://traefik.github.io/charts
      remoteChart: traefik
      # createNamespace: true
      # namespace: traefik
      valuesFiles:
        - ./helm_values/traefik.yml
      setValues:
        dashboard.enabled: true
        dashboard.domain: "traefik.localhost"
        dashboard.ingressRoute: "true"
        ingressRoute.dashboard.entryPoints: ['websecure']
    #
    # HELM: kubernetes-dashboard
    #
    - name: kubernetes-dashboard
      # createNamespace: true
      # namespace: kubernetes-dashboard
      repo:  https://kubernetes.github.io/dashboard
      remoteChart: kubernetes-dashboard
    # 
    # HELM: kube-prometheus
    #
    - name: kube-prometheus
      # createNamespace: true
      # namespace: monitoring
      repo: https://prometheus-community.github.io/helm-charts
      remoteChart: kube-prometheus-stack
      valuesFiles:
        - ./helm_values/kube-prometheus-stack.yaml
    # Helm Hooks
    hooks:
      before:
        - host:
            command: ["sh", "-c", "echo helm pre-deploy host hook running on $(hostname)!"]
      after:
        - host:
            command: ["sh", "-c", "echo helm post-deploy host hook running on $(hostname)!"]

profiles:
  - name: truenas-storage-classes
    # STORAGE DRIVER CONFIGURATION
    # - nfs-ephemeral, iscsi-ephemeral, nfs-persistent, iscsi-persistent
    # For a given env/profile we are going to create different storage-classes with the above names, or 1 with multiple aliases
    # storage-clases provided:
    #   - nfs-ephemeral, 
    #   - iscsi-ephemeral, 
    #   - nfs-persistentm, 
    #   - iscsi-persistent
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: democratic-csi
          repo: https://democratic-csi.github.io/charts/
          remoteChart: democratic-csi
          valuesFiles:
            - ./modules/valhalla-envs/values/nfs-ephemeral.yaml
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: democratic-csi
          repo: https://democratic-csi.github.io/charts/
          remoteChart: democratic-csi
          valuesFiles:
            - ./modules/valhalla-envs/values/nfs-persistent.yaml
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: democratic-csi
          repo: https://democratic-csi.github.io/charts/
          remoteChart: democratic-csi
          valuesFiles:
            - ./modules/valhalla-envs/values/iscsi-ephemeral.yaml
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: democratic-csi
          repo: https://democratic-csi.github.io/charts/
          remoteChart: democratic-csi
          valuesFiles:
            - ./modules/valhalla-envs/values/iscsi-persistent.yaml
  - name: local-storage-classes
    # TODO: WIP
    manifests:
      rawYaml:
        - ./local-storage-classes/*.yaml
  # Cloudflare DDNS
  - name: ddns
    manifests:
      rawYaml:
        - ./stacks/cloudflare-ddns/*.yaml
portForward:
  #  TODO: move these to the traefik folder as services (skaffold will auto port forward)
  - resourceType: service
    resourceName: kubernetes-dashboard
    namespace: default
    port: 443
    localPort: 8443
  - resourceType: service
    resourceName: traefik
    namespace: default
    port: 443
    localPort: 443
  - resourceType: service
    resourceName: traefik
    namespace: default
    port: 80
    localPort: 80


