version: "3"

services:

  pgdb:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - ./volumes/postgres:/bitnami/postgresql
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./volumes/mongodb:/data/db

  minio:
    image: minio/minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":${MINIO_API_PORT:-9000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_API_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  qdrant:
    image: qdrant/qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - ./volumes/qdrant:/qdrant/storage
