apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment-prod.yaml
- path: service-prod.yaml

configMapGenerator:
- name: example-configmap-1
  files:
  - ../../../../modules/private_envs/localhost.env