apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
      environment: drogon
  strategy: {}
  template:
    metadata:
      labels:
        app: cloudflare-ddns
        environment: drogon
    spec:
      containers:
        - env:
            - name: API_KEY
              value: $CF_API_KEY
            - name: PROXIED
              value: "true"
            - name: ZONE
              value: k8-lab-external
          image: oznu/cloudflare-ddns:latest
          name: cloudflare-ddns
          resources: {}
      restartPolicy: Always
status: {}
