services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
    # OPTIONAL: Expose the GUI port
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  #  add prom scraping here see documentation in this image repo
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://admin:admin@rabbitmq:5672//
      # TODO: change the celery results backend to postgresql from rediss
      # - CELERY_RESULT_BACKEND=postgresql://postgres:postgres@postgres:5432/postgres
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # - FLOWER_PORT=8888
      - FLOWER_UNAUTHENTICATED_API=true
    ports:
      - 5555:5555
    command: celery flower --broker_api=http://admin:admin@rabbitmq:15672/api//
    depends_on: 
      - rabbitmq

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data

  redis-insights:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    depends_on:
      - redis

      