log:
  level: "DEBUG"

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
  websecure:
    address: ":443"
    # http:
    #   tls:
    #     certResolver: letsencrypt

# certificatesResolvers:
#   # Set up LetsEncrypt
#   letsencrypt:
#     acme:
#       email: djdanielsh@gmail.com
#       storage: /letsencrypt/acme.json
#       dnschallenge:
#         provider: cloudflare
