---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-incomplete
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /megapool/downloads/incomplete
    server: truenas.localdomain