apiVersion: v1
kind: PersistentVolume
metadata:
  name: px200
spec:
  capacity:
    storage: 65Ti
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - hard
  - nfsvers=4
  nfs:
    path: /megapool/px200
    server: truenas.localdomain
