---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-completed
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /megapool/downloads/completed
    server: truenas.localdomain