---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv
spec:
  capacity:
    storage: 25Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: /megapool/media/tv
    server: truenas.localdomain