# Best way to test this it to create host aliases.
# knowledgedump.space
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: default
  # namespace: traefik
spec:
  acme:
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: djdanielsh@gmail.com.com
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
    - dns01:
        cloudflare:
          email: djdanielsh@gmail.com
          apiTokenSecretRef:
            name: cloudflare
            key: AUTH_KEY
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
  namespace: default
  # namespace: traefik
spec:
  secretName: wildcard-example-com-tls
  dnsNames:
  - "knowledgedump.space"
  - "*.knowledgedump.space"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
