apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - match: Host(`grafana.localhost`)
    kind: Rule
    middlewares:
    - name: headers-default
    services:
    - name: kube-prometheus-grafana
      namespace: monitoring
      port: 80

